# shopify.app.toml
client_id = "046d5a3a8fc8b6933822e2e272ebd8b3"
name = "ecuador-shipping"
handle = "ecuador-shipping"

# URL estable (puede ser tu sitio)
application_url = "https://elpeluquero.ec/pages/ecuador-shipping"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-07"  # estable
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"
[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_shipping"

[auth]
# Como no usas backend embebido ahora, puedes dejarlo vacío
redirect_urls = []

[pos]
embedded = false
