api_version = "2024-07"
[[extensions]]
name = "checkout-ui-ciudades"
handle = "checkout-ui-ciudades"
type = "ui_extension"

  [[extensions.targeting]]
  target = "purchase.checkout.delivery-address.render-after"
  module = "./src/Checkout.tsx"

[extensions.capabilities]
api_access = true
network_access = true