export const citiesToSeed = [
    { name: "COJITAMBO", province: "AZOGUES", routeName: "Especial" },
    { name: "BAÑOS (AZUAY)", province: "AZUAY", routeName: "Especial" },
    { name: "CHORDELEG", province: "AZUAY", routeName: "Especial" },
    { name: "CUENCA", province: "AZUAY", routeName: "Cantonal/Provincial" },
    { name: "CUMBE", province: "AZUAY", routeName: "Especial" },
    { name: "EL PAN", province: "AZUAY", routeName: "Especial" },
    { name: "GIRON", province: "AZUAY", routeName: "Especial" },
    { name: "GUACHAPALA", province: "AZUAY", routeName: "Especial" },
    { name: "GUALACEO", province: "AZUAY", routeName: "Cantonal/Provincial" },
    { name: "LA UNION (AZUAY)", province: "AZUAY", routeName: "Especial" },
    { name: "PAUTE", province: "AZUAY", routeName: "Especial" },
    { name: "PONCE ENRIQUEZ", province: "AZUAY", routeName: "Especial" },
    { name: "RICAURTE (AZUAY)", province: "AZUAY", routeName: "Especial" },
    { name: "SAN FERNANDO", province: "AZUAY", routeName: "Especial" },
    { name: "SANTA ISABEL", province: "AZUAY", routeName: "Especial" },
    { name: "SEVILLA DE ORO", province: "AZUAY", routeName: "Especial" },
    { name: "SIGSIG", province: "AZUAY", routeName: "Especial" },
    { name: "TARQUI (AZUAY)", province: "AZUAY", routeName: "Especial" },
    { name: "1ERO DE MAYO", province: "BOLIVAR", routeName: "Especial" },
    { name: "4 ESQUINAS", province: "BOLIVAR", routeName: "Especial" },
    { name: "ASUNCION", province: "BOLIVAR", routeName: "Especial" },
    { name: "BALZAPAMBA", province: "BOLIVAR", routeName: "Especial" },
    { name: "CALUMA", province: "BOLIVAR", routeName: "Especial" },
    { name: "CHILLANES", province: "BOLIVAR", routeName: "Especial" },
    { name: "CHIMBO", province: "BOLIVAR", routeName: "Especial" },
    { name: "GUARANDA", province: "BOLIVAR", routeName: "Regional" },
    { name: "LA MAGDALENA", province: "BOLIVAR", routeName: "Especial" },
    { name: "PISAGUA ALTO", province: "BOLIVAR", routeName: "Especial" },
    { name: "PISAGUA BAJO", province: "BOLIVAR", routeName: "Especial" },
    { name: "RECINTO 24 DE MAYO", province: "BOLIVAR", routeName: "Especial" },
    { name: "RECINTO EL PALMAR", province: "BOLIVAR", routeName: "Especial" },
    { name: "RECINTO LA MARITZA", province: "BOLIVAR", routeName: "Especial" },
    { name: "SALINAS (BOLIVAR)", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN JOSE DE CHIMBO", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN LORENZO", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN MIGUEL DE BOLIVAR", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN PABLO DE ATENAS", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN PEDRO DE GUANUJO", province: "BOLIVAR", routeName: "Especial" },
    { name: "SAN SIMON", province: "BOLIVAR", routeName: "Especial" },
    { name: "SANTA FE", province: "BOLIVAR", routeName: "Especial" },
    { name: "VINCHOA", province: "BOLIVAR", routeName: "Especial" },
    { name: "AZOGUES", province: "CAÑAR", routeName: "Cantonal/Provincial" },
    { name: "BIBLIAN", province: "CAÑAR", routeName: "Especial" },
    { name: "CAÑAR", province: "CAÑAR", routeName: "Especial" },
    { name: "COCHANCAY", province: "CAÑAR", routeName: "Especial" },
    { name: "DELEG (AZUAY)", province: "CAÑAR", routeName: "Especial" },
    { name: "DUCUR", province: "CAÑAR", routeName: "Especial" },
    { name: "GUAPAN", province: "CAÑAR", routeName: "Especial" },
    { name: "INGAPIRCA", province: "CAÑAR", routeName: "Especial" },
    { name: "JAVIER LOYOLA", province: "CAÑAR", routeName: "Especial" },
    { name: "LA PUNTILLA - EL TRIUNFO", province: "CAÑAR", routeName: "Especial" },
    { name: "LA TRONCAL", province: "CAÑAR", routeName: "Especial" },
    { name: "SUSCAL", province: "CAÑAR", routeName: "Especial" },
    { name: "TAMBO", province: "CAÑAR", routeName: "Especial" },
    { name: "VOLUNTAD DE DIOS", province: "CAÑAR", routeName: "Especial" },
    { name: "BOLIVAR", province: "CARCHI", routeName: "Especial" },
    { name: "CHITAN DE NAVARRETES", province: "CARCHI", routeName: "Especial" },
    { name: "CRISTOBAL COLON", province: "CARCHI", routeName: "Especial" },
    { name: "CUESACA", province: "CARCHI", routeName: "Especial" },
    { name: "EL ANGEL", province: "CARCHI", routeName: "Especial" },
    { name: "GARCIA MORENO", province: "CARCHI", routeName: "Especial" },
    { name: "HUACA", province: "CARCHI", routeName: "Especial" },
    { name: "JULIO ANDRADE", province: "CARCHI", routeName: "Especial" },
    { name: "LA PAZ", province: "CARCHI", routeName: "Especial" },
    { name: "MIRA", province: "CARCHI", routeName: "Especial" },
    { name: "SAN GABRIEL", province: "CARCHI", routeName: "Especial" },
    { name: "SAN ISIDRO (CARCHI SAN GABRIEL)", province: "CARCHI", routeName: "Especial" },
    { name: "TULCAN", province: "CARCHI", routeName: "Regional" },
    { name: "PIOTER", province: "CARCHI SAN GABRIEL", routeName: "Especial" },
    { name: "SANDIAL", province: "CARCHI SAN GABRIEL", routeName: "Especial" },
    { name: "SANTA MARTHA DE CUBA", province: "CARCHI SAN GABRIEL", routeName: "Especial" },
    { name: "ALAUSI", province: "CHIMBORAZO", routeName: "Regional" },
    { name: "CAJABAMBA", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "CHAMBO", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "CHUNCHI", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "COLTA", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "EL GUANO", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "GUAMOTE", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "LICAN", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "PALLATANGA", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "PENIPE", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "RIOBAMBA", province: "CHIMBORAZO", routeName: "Regional" },
    { name: "SAN ANDRES", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "SAN LUIS (CHIMBORAZO)", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "YARUQUIES", province: "CHIMBORAZO", routeName: "Especial" },
    { name: "ANCHILIVI", province: "COTOPAXI", routeName: "Especial" },
    { name: "BELISARIO QUEVEDO", province: "COTOPAXI", routeName: "Especial" },
    { name: "CHIPUALO", province: "COTOPAXI", routeName: "Especial" },
    { name: "EL CORAZON", province: "COTOPAXI", routeName: "Especial" },
    { name: "GUAYTACAMA", province: "COTOPAXI", routeName: "Especial" },
    { name: "LA MANA", province: "COTOPAXI", routeName: "Especial" },
    { name: "LA VICTORIA", province: "COTOPAXI", routeName: "Especial" },
    { name: "LASSO", province: "COTOPAXI", routeName: "Especial" },
    { name: "LATACUNGA", province: "COTOPAXI", routeName: "Regional" },
    { name: "MORASPUNGO", province: "COTOPAXI", routeName: "Especial" },
    { name: "MULALAO", province: "COTOPAXI", routeName: "Especial" },
    { name: "MULALILLO", province: "COTOPAXI", routeName: "Especial" },
    { name: "PANGUA", province: "COTOPAXI", routeName: "Especial" },
    { name: "PANZALEO", province: "COTOPAXI", routeName: "Especial" },
    { name: "PASTOCALLE", province: "COTOPAXI", routeName: "Especial" },
    { name: "PATAIN", province: "COTOPAXI", routeName: "Especial" },
    { name: "POALO", province: "COTOPAXI", routeName: "Especial" },
    { name: "PUJILI", province: "COTOPAXI", routeName: "Especial" },
    { name: "RUMIPAMBA", province: "COTOPAXI", routeName: "Especial" },
    { name: "SALCEDO", province: "COTOPAXI", routeName: "Especial" },
    { name: "SAN MARCOS", province: "COTOPAXI", routeName: "Especial" },
    { name: "SANTA ANA (COTOPAXI)", province: "COTOPAXI", routeName: "Especial" },
    { name: "SAQUISILI", province: "COTOPAXI", routeName: "Especial" },
    { name: "SIGCHOS", province: "COTOPAXI", routeName: "Especial" },
    { name: "TANICUCHI", province: "COTOPAXI", routeName: "Especial" },
    { name: "TOACASO", province: "COTOPAXI", routeName: "Especial" },
    { name: "YANAYACU", province: "COTOPAXI", routeName: "Especial" },
    { name: "3 CERRITOS (PASAJE)", province: "EL ORO", routeName: "Especial" },
    { name: "ARENILLAS", province: "EL ORO", routeName: "Especial" },
    { name: "BAJO ALTO", province: "EL ORO", routeName: "Especial" },
    { name: "BALSAS", province: "EL ORO", routeName: "Especial" },
    { name: "BARBONES", province: "EL ORO", routeName: "Especial" },
    { name: "BELLAMARIA", province: "EL ORO", routeName: "Especial" },
    { name: "BUENA VISTA", province: "EL ORO", routeName: "Especial" },
    { name: "CAÑA QUEMADA", province: "EL ORO", routeName: "Especial" },
    { name: "EL CAMBIO", province: "EL ORO", routeName: "Especial" },
    { name: "EL GUABO", province: "EL ORO", routeName: "Especial" },
    { name: "EL PACHE", province: "EL ORO", routeName: "Especial" },
    { name: "EL PORTON", province: "EL ORO", routeName: "Especial" },
    { name: "HUAQUILLAS", province: "EL ORO", routeName: "Cantonal/Provincial" },
    { name: "LA AVANZADA", province: "EL ORO", routeName: "Especial" },
    { name: "LA IBERIA", province: "EL ORO", routeName: "Especial" },
    { name: "LA PEAÑA", province: "EL ORO", routeName: "Especial" },
    { name: "LOMA DE FRANCO", province: "EL ORO", routeName: "Especial" },
    { name: "LOURDES", province: "EL ORO", routeName: "Especial" },
    { name: "MACHALA", province: "EL ORO", routeName: "Cantonal/Provincial" },
    { name: "MARCABELI", province: "EL ORO", routeName: "Especial" },
    { name: "NUEVO PUENTE INTERNACIONAL CEBEF", province: "EL ORO", routeName: "Especial" },
    { name: "PASAJE", province: "EL ORO", routeName: "Especial" },
    { name: "PIÑAS", province: "EL ORO", routeName: "Especial" },
    { name: "PORTOVELO", province: "EL ORO", routeName: "Especial" },
    { name: "PUERTO BOLIVAR", province: "EL ORO", routeName: "Especial" },
    { name: "PUERTO HUALTACO", province: "EL ORO", routeName: "Especial" },
    { name: "PUERTO JELI", province: "EL ORO", routeName: "Especial" },
    { name: "RIO BONITO", province: "EL ORO", routeName: "Especial" },
    { name: "SAN VICENTE DEL JOBO", province: "EL ORO", routeName: "Especial" },
    { name: "SANTA ROSA (EL ORO)", province: "EL ORO", routeName: "Especial" },
    { name: "SHUMIRAL", province: "EL ORO", routeName: "Especial" },
    { name: "ZARUMA", province: "EL ORO", routeName: "Especial" },
    { name: "ATACAMES", province: "ESMERALDAS", routeName: "Especial" },
    { name: "BORBON", province: "ESMERALDAS", routeName: "Especial" },
    { name: "ESMERALDAS", province: "ESMERALDAS", routeName: "Regional" },
    { name: "LA CONCORDIA", province: "ESMERALDAS", routeName: "Especial" },
    { name: "LA INDEPENDENCIA", province: "ESMERALDAS", routeName: "Especial" },
    { name: "LA UNION (QUININDE)", province: "ESMERALDAS", routeName: "Especial" },
    { name: "LA Y DE CALDERON", province: "ESMERALDAS", routeName: "Especial" },
    { name: "LAGARTO", province: "ESMERALDAS", routeName: "Especial" },
    { name: "LAS PEÑAS", province: "ESMERALDAS", routeName: "Especial" },
    { name: "MUISNE", province: "ESMERALDAS", routeName: "Especial" },
    { name: "QUININDE", province: "ESMERALDAS", routeName: "Especial" },
    { name: "RIO VERDE", province: "ESMERALDAS", routeName: "Especial" },
    { name: "SAME", province: "ESMERALDAS", routeName: "Especial" },
    { name: "SAN LORENZO", province: "ESMERALDAS", routeName: "Especial" },
    { name: "SUA", province: "ESMERALDAS", routeName: "Especial" },
    { name: "TACHINA", province: "ESMERALDAS", routeName: "Especial" },
    { name: "TONCHIGUE", province: "ESMERALDAS", routeName: "Especial" },
    { name: "TONSUPA", province: "ESMERALDAS", routeName: "Especial" },
    { name: "VICHE", province: "ESMERALDAS", routeName: "Especial" },
    { name: "SAN CRISTOBAL - PUERTO BAQUERIZO MORENO", province: "GALAPAGOS", routeName: "Galápagos" },
    { name: "SANTA CRUZ - PUERTO AYORA", province: "GALAPAGOS", routeName: "Galápagos" },
    { name: "3 POSTES", province: "GUAYAS", routeName: "Especial" },
    { name: "ALFREDO BAQUERIZO MORENO", province: "GUAYAS", routeName: "Especial" },
    { name: "JUJAN", province: "GUAYAS", routeName: "Especial" },
    { name: "BUCAY", province: "GUAYAS", routeName: "Especial" },
    { name: "GENERAL ANTONIO ELIZALDE", province: "GUAYAS", routeName: "Especial" },
    { name: "MATILDE ESTHER", province: "GUAYAS", routeName: "Especial" },
    { name: "CUMANDA", province: "GUAYAS", routeName: "Especial" },
    { name: "DAULE", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "EL EMPALME", province: "GUAYAS", routeName: "Especial" },
    { name: "EL TRIUNFO", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "MANUEL J CALLE", province: "GUAYAS", routeName: "Especial" },
    { name: "CHONGON", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "DURAN - ELOY ALFARO", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "ELOY ALFARO - DURAN", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "GUAYAQUIL", province: "GUAYAS", routeName: "Local" },
    { name: "LA PUNTILLA", province: "GUAYAS", routeName: "Local" },
    { name: "INGENIO SAN CARLOS", province: "GUAYAS", routeName: "Especial" },
    { name: "LORENZO DE GARAICOA", province: "GUAYAS", routeName: "Especial" },
    { name: "MARCELINO MARIDUEÑA", province: "GUAYAS", routeName: "Especial" },
    { name: "MARISCAL SUCRE", province: "GUAYAS", routeName: "Especial" },
    { name: "NARANJITO", province: "GUAYAS", routeName: "Especial" },
    { name: "ROBERTO ASTUDILLO", province: "GUAYAS", routeName: "Especial" },
    { name: "SIMON BOLIVAR", province: "GUAYAS", routeName: "Especial" },
    { name: "BOCA DE CAÑA", province: "GUAYAS", routeName: "Especial" },
    { name: "COLORADAL", province: "GUAYAS", routeName: "Especial" },
    { name: "GENERAL VERNAZA", province: "GUAYAS", routeName: "Especial" },
    { name: "LA MARAVILLA", province: "GUAYAS", routeName: "Especial" },
    { name: "LA T DE SALITRE", province: "GUAYAS", routeName: "Especial" },
    { name: "LAS ANIMAS", province: "GUAYAS", routeName: "Especial" },
    { name: "LAUREL", province: "GUAYAS", routeName: "Especial" },
    { name: "LOS TINTOS", province: "GUAYAS", routeName: "Especial" },
    { name: "SANTA LUCIA", province: "GUAYAS", routeName: "Especial" },
    { name: "TARIFA", province: "GUAYAS", routeName: "Especial" },
    { name: "URBINA JADO - SALITRE", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "BALZAR", province: "GUAYAS", routeName: "Especial" },
    { name: "COLIMES", province: "GUAYAS", routeName: "Especial" },
    { name: "PALESTINA", province: "GUAYAS", routeName: "Especial" },
    { name: "SALITRE - URBINA JADO", province: "GUAYAS", routeName: "Especial" },
    { name: "SAMBORONDON", province: "GUAYAS", routeName: "Especial" },
    { name: "TENGUEL", province: "GUAYAS", routeName: "Especial" },
    { name: "MILAGRO", province: "GUAYAS", routeName: "Cantonal/Provincial" },
    { name: "BALAO (NARANJAL)", province: "GUAYAS", routeName: "Especial" },
    { name: "BALAO CHICO (NARANJAL)", province: "GUAYAS", routeName: "Especial" },
    { name: "CIEN FAMILIA", province: "GUAYAS", routeName: "Especial" },
    { name: "LAS MERCEDES (NARANJAL)", province: "GUAYAS", routeName: "Especial" },
    { name: "NARANJAL", province: "GUAYAS", routeName: "Especial" },
    { name: "NUEVA UNION (NARANJAL)", province: "GUAYAS", routeName: "Especial" },
    { name: "PUERTO INCA", province: "GUAYAS", routeName: "Especial" },
    { name: "SAN CARLOS (BALAO)", province: "GUAYAS", routeName: "Especial" },
    { name: "SANTA RITA (BALAO)", province: "GUAYAS", routeName: "Especial" },
    { name: "VILLA NUEVA", province: "GUAYAS", routeName: "Especial" },
    { name: "CHIVERIA", province: "GUAYAS", routeName: "Especial" },
    { name: "EL NATO", province: "GUAYAS", routeName: "Especial" },
    { name: "ISIDRO AYORA", province: "GUAYAS", routeName: "Especial" },
    { name: "LA TOMA (GUAYAS)", province: "GUAYAS", routeName: "Especial" },
    { name: "LOMAS DE SARGENTILLO", province: "GUAYAS", routeName: "Especial" },
    { name: "NOBOL", province: "GUAYAS", routeName: "Especial" },
    { name: "PEDRO CARBO", province: "GUAYAS", routeName: "Especial" },
    { name: "PETRILLO", province: "GUAYAS", routeName: "Especial" },
    { name: "PUENTE LUCIA", province: "GUAYAS", routeName: "Especial" },
    { name: "SABANILLA (PEDRO CARBO)", province: "GUAYAS", routeName: "Especial" },
    { name: "SAN ISIDRO (GUAYAS)", province: "GUAYAS", routeName: "Especial" },
    { name: "CERECITA", province: "GUAYAS", routeName: "Especial" },
    { name: "DATA DE PLAYAS", province: "GUAYAS", routeName: "Especial" },
    { name: "EL MORRO", province: "GUAYAS", routeName: "Especial" },
    { name: "ENGABAO", province: "GUAYAS", routeName: "Especial" },
    { name: "PLAYAS", province: "GUAYAS", routeName: "Especial" },
    { name: "POSORJA", province: "GUAYAS", routeName: "Especial" },
    { name: "PROGRESO", province: "GUAYAS", routeName: "Especial" },
    { name: "PUERTO DEL ENGABAO", province: "GUAYAS", routeName: "Especial" },
    { name: "SAN ANTONIO (PLAYAS)", province: "GUAYAS", routeName: "Especial" },
    { name: "BASE TAURA", province: "GUAYAS", routeName: "Especial" },
    { name: "BOLICHE", province: "GUAYAS", routeName: "Especial" },
    { name: "EL DESEO", province: "GUAYAS", routeName: "Especial" },
    { name: "KM 26 - VIRGEN DE FATIMA", province: "GUAYAS", routeName: "Especial" },
    { name: "VIRGEN DE FATIMA KM 26", province: "GUAYAS", routeName: "Especial" },
    { name: "SAN JACINTO DE YAGUACHI", province: "GUAYAS", routeName: "Especial" },
    { name: "YAGUACHI", province: "GUAYAS", routeName: "Especial" },
    { name: "ADUANA", province: "IMBABURA", routeName: "Especial" },
    { name: "ALPACHACA", province: "IMBABURA", routeName: "Especial" },
    { name: "ANDRADE MARIN", province: "IMBABURA", routeName: "Especial" },
    { name: "ANTONIO ANTE", province: "IMBABURA", routeName: "Especial" },
    { name: "ATUNTAQUI", province: "IMBABURA", routeName: "Especial" },
    { name: "CARANQUI", province: "IMBABURA", routeName: "Especial" },
    { name: "CHALTURA", province: "IMBABURA", routeName: "Especial" },
    { name: "CHORLAVI", province: "IMBABURA", routeName: "Especial" },
    { name: "COTACACHI", province: "IMBABURA", routeName: "Especial" },
    { name: "EL OLIVO", province: "IMBABURA", routeName: "Especial" },
    { name: "EL RETORNO", province: "IMBABURA", routeName: "Especial" },
    { name: "IBARRA", province: "IMBABURA", routeName: "Regional" },
    { name: "NATABUELA", province: "IMBABURA", routeName: "Especial" },
    { name: "OTAVALO", province: "IMBABURA", routeName: "Especial" },
    { name: "PIMAMPIRO", province: "IMBABURA", routeName: "Especial" },
    { name: "PINSAQUI", province: "IMBABURA", routeName: "Especial" },
    { name: "PUERTO LAGO", province: "IMBABURA", routeName: "Especial" },
    { name: "QUIROGA", province: "IMBABURA", routeName: "Especial" },
    { name: "SAN ANTONIO DE IBARRA", province: "IMBABURA", routeName: "Especial" },
    { name: "SAN JOSE", province: "IMBABURA", routeName: "Especial" },
    { name: "SAN LUIS (IMBABURA)", province: "IMBABURA", routeName: "Especial" },
    { name: "SAN PABLO DEL LAGO", province: "IMBABURA", routeName: "Especial" },
    { name: "SAN ROQUE", province: "IMBABURA", routeName: "Especial" },
    { name: "SANTO DOMINGO IMBABURA", province: "IMBABURA", routeName: "Especial" },
    { name: "URCUQUI", province: "IMBABURA", routeName: "Especial" },
    { name: "YACHAI", province: "IMBABURA", routeName: "Especial" },
    { name: "YAGUARCOCHA", province: "IMBABURA", routeName: "Especial" },
    { name: "ALAMOR", province: "LOJA", routeName: "Especial" },
    { name: "CARIAMANGA", province: "LOJA", routeName: "Especial" },
    { name: "CATACOCHA", province: "LOJA", routeName: "Especial" },
    { name: "CATAMAYO", province: "LOJA", routeName: "Especial" },
    { name: "CELICA", province: "LOJA", routeName: "Especial" },
    { name: "CHAGUARPAMBA", province: "LOJA", routeName: "Especial" },
    { name: "GONZANAMA", province: "LOJA", routeName: "Especial" },
    { name: "LOJA", province: "LOJA", routeName: "Cantonal/Provincial" },
    { name: "MACARA", province: "LOJA", routeName: "Especial" },
    { name: "MALACATOS", province: "LOJA", routeName: "Especial" },
    { name: "OLMEDO (LOJA)", province: "LOJA", routeName: "Especial" },
    { name: "PINDAL", province: "LOJA", routeName: "Especial" },
    { name: "POZUL", province: "LOJA", routeName: "Especial" },
    { name: "SAN LUCAS", province: "LOJA", routeName: "Especial" },
    { name: "SANTIAGO", province: "LOJA", routeName: "Especial" },
    { name: "SARAGURO", province: "LOJA", routeName: "Especial" },
    { name: "SOZORANGA", province: "LOJA", routeName: "Especial" },
    { name: "VILCABAMBA", province: "LOJA", routeName: "Especial" },
    { name: "ZAPOTILLO", province: "LOJA", routeName: "Especial" },
    { name: "BABA", province: "LOS RIOS", routeName: "Especial" },
    { name: "BABAHOYO", province: "LOS RIOS", routeName: "Cantonal/Provincial" },
    { name: "BUENA FE", province: "LOS RIOS", routeName: "Especial" },
    { name: "CARACOL", province: "LOS RIOS", routeName: "Especial" },
    { name: "CATARAMA", province: "LOS RIOS", routeName: "Especial" },
    { name: "ECHEANDIA", province: "LOS RIOS", routeName: "Especial" },
    { name: "ENTRADA DE SAN JUAN", province: "LOS RIOS", routeName: "Especial" },
    { name: "FUMISA", province: "LOS RIOS", routeName: "Especial" },
    { name: "HIDROLITORAL", province: "LOS RIOS", routeName: "Especial" },
    { name: "ISLA DE BEJUCAL", province: "LOS RIOS", routeName: "Especial" },
    { name: "LA 14 VIA EL PARAISO", province: "LOS RIOS", routeName: "Especial" },
    { name: "LA ESPERANZA", province: "LOS RIOS", routeName: "Especial" },
    { name: "LA JULIA", province: "LOS RIOS", routeName: "Especial" },
    { name: "LA UNION (BABAHOYO)", province: "LOS RIOS", routeName: "Especial" },
    { name: "LA UNION (VALENCIA)", province: "LOS RIOS", routeName: "Especial" },
    { name: "LAS NAVES", province: "LOS RIOS", routeName: "Especial" },
    { name: "LOS ANGELES - RECINTO", province: "LOS RIOS", routeName: "Especial" },
    { name: "MATA DE CACAO", province: "LOS RIOS", routeName: "Especial" },
    { name: "MOCACHE", province: "LOS RIOS", routeName: "Especial" },
    { name: "MONTALVO", province: "LOS RIOS", routeName: "Especial" },
    { name: "NUEVA UNION (LOS RIOS)", province: "LOS RIOS", routeName: "Especial" },
    { name: "PALENQUE", province: "LOS RIOS", routeName: "Especial" },
    { name: "PALMISA", province: "LOS RIOS", routeName: "Especial" },
    { name: "PATRICIA PILAR", province: "LOS RIOS", routeName: "Especial" },
    { name: "PUEBLO NUEVO (LOS RIOS)", province: "LOS RIOS", routeName: "Especial" },
    { name: "PUEBLO VIEJO", province: "LOS RIOS", routeName: "Especial" },
    { name: "QUEVEDO", province: "LOS RIOS", routeName: "Cantonal/Provincial" },
    { name: "QUINSALOMA", province: "LOS RIOS", routeName: "Especial" },
    { name: "RICAURTE (LOS RIOS)", province: "LOS RIOS", routeName: "Especial" },
    { name: "SAN CAMILO", province: "LOS RIOS", routeName: "Especial" },
    { name: "SAN CARLOS (LOS RIOS)", province: "LOS RIOS", routeName: "Especial" },
    { name: "SAN JUAN", province: "LOS RIOS", routeName: "Especial" },
    { name: "SAN LUIS DE PAMBIL", province: "LOS RIOS", routeName: "Especial" },
    { name: "URDANETA", province: "LOS RIOS", routeName: "Especial" },
    { name: "VALENCIA", province: "LOS RIOS", routeName: "Especial" },
    { name: "VENTANAS", province: "LOS RIOS", routeName: "Cantonal/Provincial" },
    { name: "VINCES", province: "LOS RIOS", routeName: "Especial" },
    { name: "ZAPOTAL (LOS RIOS)", province: "LOS RIOS", routeName: "Especial" },
    { name: "ZULEMA", province: "LOS RIOS", routeName: "Especial" },
    { name: "10 DE AGOSTO", province: "MANABI", routeName: "Especial" },
    { name: "24 DE MAYO", province: "MANABI", routeName: "Especial" },
    { name: "ARENALES", province: "MANABI", routeName: "Especial" },
    { name: "ATAHUALPA MANABI", province: "MANABI", routeName: "Especial" },
    { name: "BACHILLERO", province: "MANABI", routeName: "Especial" },
    { name: "BAHIA DE CARAQUEZ", province: "MANABI", routeName: "Cantonal/Provincial" },
    { name: "BELLAVISTA", province: "MANABI", routeName: "Especial" },
    { name: "CALCETA", province: "MANABI", routeName: "Especial" },
    { name: "CALDERON (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "CANOA", province: "MANABI", routeName: "Especial" },
    { name: "CANUTO", province: "MANABI", routeName: "Especial" },
    { name: "CAÑITAS", province: "MANABI", routeName: "Especial" },
    { name: "CASCOL", province: "MANABI", routeName: "Especial" },
    { name: "CHARAPOTO", province: "MANABI", routeName: "Especial" },
    { name: "CHEVE", province: "MANABI", routeName: "Especial" },
    { name: "CHONE", province: "MANABI", routeName: "Cantonal/Provincial" },
    { name: "CIUDAD ALFARO", province: "MANABI", routeName: "Especial" },
    { name: "COAQUE", province: "MANABI", routeName: "Especial" },
    { name: "COJIMIES", province: "MANABI", routeName: "Especial" },
    { name: "COLON", province: "MANABI", routeName: "Especial" },
    { name: "COLORADO", province: "MANABI", routeName: "Especial" },
    { name: "CRUCITA", province: "MANABI", routeName: "Especial" },
    { name: "DON JUAN", province: "MANABI", routeName: "Especial" },
    { name: "EL CARMEN", province: "MANABI", routeName: "Especial" },
    { name: "EL MATAL", province: "MANABI", routeName: "Especial" },
    { name: "EL RODEO", province: "MANABI", routeName: "Especial" },
    { name: "FLAVIO ALFARO", province: "MANABI", routeName: "Especial" },
    { name: "JAMA", province: "MANABI", routeName: "Especial" },
    { name: "JARAMIJO", province: "MANABI", routeName: "Especial" },
    { name: "JIPIJAPA", province: "MANABI", routeName: "Cantonal/Provincial" },
    { name: "JUNIN", province: "MANABI", routeName: "Especial" },
    { name: "LA CHORRERA", province: "MANABI", routeName: "Especial" },
    { name: "LA ESTANCILLA", province: "MANABI", routeName: "Especial" },
    { name: "LEONIDAS PLAZA", province: "MANABI", routeName: "Especial" },
    { name: "LODANA", province: "MANABI", routeName: "Especial" },
    { name: "LOS BAJOS", province: "MANABI", routeName: "Especial" },
    { name: "MACHALILLA", province: "MANABI", routeName: "Especial" },
    { name: "MACHE", province: "MANABI", routeName: "Especial" },
    { name: "MANTA", province: "MANABI", routeName: "Cantonal/Provincial" },
    { name: "MONTECRISTI", province: "MANABI", routeName: "Especial" },
    { name: "NUEVO BRICEÑO", province: "MANABI", routeName: "Especial" },
    { name: "OLMEDO (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "PAJAN", province: "MANABI", routeName: "Especial" },
    { name: "PEDERNALES", province: "MANABI", routeName: "Especial" },
    { name: "PICHINCHA", province: "MANABI", routeName: "Especial" },
    { name: "PLAYA PRIETA", province: "MANABI", routeName: "Especial" },
    { name: "PORTOVIEJO", province: "MANABI", routeName: "Cantonal/Provincial" },
    { name: "PUEBLO NUEVO (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "PUERTO LOPEZ", province: "MANABI", routeName: "Especial" },
    { name: "RICAURTE (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "RIO CHICO", province: "MANABI", routeName: "Especial" },
    { name: "ROCAFUERTE", province: "MANABI", routeName: "Especial" },
    { name: "SAN ANTONIO (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "SAN CLEMENTE", province: "MANABI", routeName: "Especial" },
    { name: "SAN ISIDRO (BAHIA)", province: "MANABI", routeName: "Especial" },
    { name: "SAN JACINTO", province: "MANABI", routeName: "Especial" },
    { name: "SAN PLACIDO", province: "MANABI", routeName: "Especial" },
    { name: "SAN VICENTE", province: "MANABI", routeName: "Especial" },
    { name: "SANCAN", province: "MANABI", routeName: "Especial" },
    { name: "SANTA ANA (MANABI)", province: "MANABI", routeName: "Especial" },
    { name: "SOSOTE", province: "MANABI", routeName: "Especial" },
    { name: "SUCRE - BAHIA", province: "MANABI", routeName: "Especial" },
    { name: "TOSAGUA", province: "MANABI", routeName: "Especial" },
    { name: "GUALAQUIZA", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "LIMON INDANZA", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "MACAS", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "MENDEZ", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "PALORA", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "SUCUA", province: "MORONA SANTIAGO", routeName: "Especial" },
    { name: "ARCHIDONA", province: "NAPO", routeName: "Especial" },
    { name: "AROSEMENA TOLA", province: "NAPO", routeName: "Especial" },
    { name: "BAEZA", province: "NAPO", routeName: "Especial" },
    { name: "BORJA", province: "NAPO", routeName: "Especial" },
    { name: "COTUNDO", province: "NAPO", routeName: "Especial" },
    { name: "EL CHACO", province: "NAPO", routeName: "Especial" },
    { name: "GONZALO PIZARRO", province: "NAPO", routeName: "Especial" },
    { name: "NUEVA ESPERANZA", province: "NAPO", routeName: "Especial" },
    { name: "PUERTO NAPO", province: "NAPO", routeName: "Especial" },
    { name: "TAZAYACU", province: "NAPO", routeName: "Especial" },
    { name: "TENA", province: "NAPO", routeName: "Especial" },
    { name: "EL COCA - FRANCISCO DE ORELLANA", province: "ORELLANA", routeName: "Especial" },
    { name: "JOYA DE LOS SACHAS", province: "ORELLANA", routeName: "Especial" },
    { name: "LORETO", province: "ORELLANA", routeName: "Especial" },
    { name: "MERA", province: "PASTAZA", routeName: "Especial" },
    { name: "PUYO", province: "PASTAZA", routeName: "Especial" },
    { name: "SANTA CLARA", province: "PASTAZA", routeName: "Especial" },
    { name: "SHELL (EL PUYO)", province: "PASTAZA", routeName: "Especial" },
    { name: "ALANGASI", province: "PICHINCHA", routeName: "Especial" },
    { name: "ALOAG", province: "PICHINCHA", routeName: "Especial" },
    { name: "ALOASI", province: "PICHINCHA", routeName: "Especial" },
    { name: "AMAGUAÑA", province: "PICHINCHA", routeName: "Especial" },
    { name: "AYORA", province: "PICHINCHA", routeName: "Especial" },
    { name: "CALACALI", province: "PICHINCHA", routeName: "Especial" },
    { name: "CALDERON (PICHINCHA)", province: "PICHINCHA", routeName: "Especial" },
    { name: "CAYAMBE", province: "PICHINCHA", routeName: "Regional" },
    { name: "CONOCOTO", province: "PICHINCHA", routeName: "Especial" },
    { name: "CUMBAYA", province: "PICHINCHA", routeName: "Especial" },
    { name: "CUSUBAMBA", province: "PICHINCHA", routeName: "Especial" },
    { name: "GUACHALA", province: "PICHINCHA", routeName: "Especial" },
    { name: "GUAYLLABAMBA", province: "PICHINCHA", routeName: "Especial" },
    { name: "JUAN MONTALVO", province: "PICHINCHA", routeName: "Especial" },
    { name: "LA ARMENIA", province: "PICHINCHA", routeName: "Especial" },
    { name: "LLANO CHICO", province: "PICHINCHA", routeName: "Regional" },
    { name: "LLANO GRANDE", province: "PICHINCHA", routeName: "Regional" },
    { name: "MACHACHI", province: "PICHINCHA", routeName: "Regional" },
    { name: "MEJIA", province: "PICHINCHA", routeName: "Especial" },
    { name: "MIRAVALLE", province: "PICHINCHA", routeName: "Especial" },
    { name: "MONJAS", province: "PICHINCHA", routeName: "Especial" },
    { name: "NANEGALITO", province: "PICHINCHA", routeName: "Especial" },
    { name: "PEDRO VICENTE MALDONADO", province: "PICHINCHA", routeName: "Especial" },
    { name: "PIFO", province: "PICHINCHA", routeName: "Especial" },
    { name: "PINTAG", province: "PICHINCHA", routeName: "Especial" },
    { name: "POMASQUI", province: "PICHINCHA", routeName: "Regional" },
    { name: "PUEMBO", province: "PICHINCHA", routeName: "Especial" },
    { name: "PUERTO QUITO", province: "PICHINCHA", routeName: "Especial" },
    { name: "PUSUQUI", province: "PICHINCHA", routeName: "Regional" },
    { name: "QUINCHE", province: "PICHINCHA", routeName: "Especial" },
    { name: "QUITO", province: "PICHINCHA", routeName: "Regional" },
    { name: "SAN ANTONIO DE PICHINCHA", province: "PICHINCHA", routeName: "Regional" },
    { name: "SAN JOSE DE MORAN", province: "PICHINCHA", routeName: "Regional" },
    { name: "SAN JUAN DE CALDERON", province: "PICHINCHA", routeName: "Regional" },
    { name: "SAN MIGUEL DE LOS BANCOS", province: "PICHINCHA", routeName: "Especial" },
    { name: "SAN RAFAEL", province: "PICHINCHA", routeName: "Especial" },
    { name: "SANGOLQUI", province: "PICHINCHA", routeName: "Especial" },
    { name: "TABABELA", province: "PICHINCHA", routeName: "Regional" },
    { name: "TABACUNDO", province: "PICHINCHA", routeName: "Especial" },
    { name: "TAMBILLO", province: "PICHINCHA", routeName: "Especial" },
    { name: "UYUMBICHO", province: "PICHINCHA", routeName: "Regional" },
    { name: "ZAMBISA", province: "PICHINCHA", routeName: "Regional" },
    { name: "ANCON", province: "SANTA ELENA", routeName: "Especial" },
    { name: "ANCONCITO", province: "SANTA ELENA", routeName: "Especial" },
    { name: "BALLENITA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "CADEATE", province: "SANTA ELENA", routeName: "Especial" },
    { name: "CAPAES", province: "SANTA ELENA", routeName: "Especial" },
    { name: "EL TAMBO", province: "SANTA ELENA", routeName: "Especial" },
    { name: "JAMBELI MONTEVERDE (SANTA ELENA)", province: "SANTA ELENA", routeName: "Especial" },
    { name: "LA LIBERTAD", province: "SANTA ELENA", routeName: "Cantonal/Provincial" },
    { name: "LIBERTADOR BOLIVAR", province: "SANTA ELENA", routeName: "Especial" },
    { name: "MANGLARALTO", province: "SANTA ELENA", routeName: "Especial" },
    { name: "MONTAÑITA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "MONTEVERDE - JAMBELI (SANTA ELENA)", province: "SANTA ELENA", routeName: "Especial" },
    { name: "MUEY", province: "SANTA ELENA", routeName: "Especial" },
    { name: "OLON", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PALMAR", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PROSPERIDAD", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PUNTA BARANDUA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PUNTA BLANCA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PUNTA CARNERO", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PUNTA CENTINELA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "SALINAS (SANTA ELENA)", province: "SANTA ELENA", routeName: "Especial" },
    { name: "SAN PABLO (SANTA ELENA)", province: "SANTA ELENA", routeName: "Especial" },
    { name: "SAN PEDRO", province: "SANTA ELENA", routeName: "Especial" },
    { name: "SANTA ELENA", province: "SANTA ELENA", routeName: "Cantonal/Provincial" },
    { name: "SANTA ROSA (SANTA ELENA)", province: "SANTA ELENA", routeName: "Especial" },
    { name: "VALDIVIA", province: "SANTA ELENA", routeName: "Especial" },
    { name: "PUERTO LIMON", province: "SANTO DOMINGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "SAN JACINTO DEL BUA", province: "SANTO DOMINGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "ALLURIQUIN", province: "STO DOMINGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "KM 14-QUEVEDO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "KM 24-QUEVEDO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "KM 38.5 VIA QUEVEDO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "KM 41 VIA QUEVEDO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "LAS DELICIAS", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "LUZ DE AMERICA", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "NUEVO ISRAEL", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "SANTO DOMINGO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Regional" },
    { name: "VALLE HERMOSO", province: "STO. DGO DE LOS TSACHILAS", routeName: "Especial" },
    { name: "7 DE JULIO", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "CASCALES", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "JIVINO VERDE", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "LAGO AGRIO", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "LOS RIOS (SUCUMBIOS)", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "LUMBAQUI", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "REVENTADOR", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "SANTA CECILIA", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "SHUSHUFINDI", province: "SUCUMBIOS", routeName: "Especial" },
    { name: "AMBATO", province: "TUNGURAHUA", routeName: "Regional" },
    { name: "BAÑOS (TUNGURAHUA)", province: "TUNGURAHUA", routeName: "Regional" },
    { name: "CEVALLOS", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "HUAMBALO", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "MOCHA", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "PATATE", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "PELILEO", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "PILLARO", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "QUERO", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "SANTA ROSA (AMBATO)", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "TISALEO", province: "TUNGURAHUA", routeName: "Especial" },
    { name: "EL PANGUI", province: "ZAMORA", routeName: "Especial" },
    { name: "PALANDA", province: "ZAMORA", routeName: "Especial" },
    { name: "YANTZAZA", province: "ZAMORA", routeName: "Especial" },
    { name: "ZAMORA", province: "ZAMORA", routeName: "Especial" },
    { name: "ZUMBA", province: "ZAMORA", routeName: "Especial" },
];
