api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "calculador-tarifas"

uid = "484a83b4-845d-5640-c2bc-7acc91f0025b0dcef953"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
